"""add show_payments

Revision ID: 02ab48a50b0a
Revises: 2f79f4efafd9
Create Date: 2026-03-27 07:51:37.726092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ab48a50b0a'
down_revision: Union[str, None] = '2f79f4efafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tontines', sa.Column('show_payments', sa.Boolean(), nullable=True))
    op.drop_column('tontines', 'payment_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tontines', sa.Column('payment_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tontines', 'show_payments')
    # ### end Alembic commands ###
