"""add show_payments

Revision ID: 144461f44dc3
Revises: 02ab48a50b0a
Create Date: 2026-03-27 07:52:51.745616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144461f44dc3'
down_revision: Union[str, None] = '02ab48a50b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tontines', sa.Column('payment_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tontines', 'payment_day')
    # ### end Alembic commands ###
