"""add avatar welcome payment_day

Revision ID: 2f79f4efafd9
Revises: 4e9ca77253be
Create Date: 2026-03-23 22:49:13.311371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79f4efafd9'
down_revision: Union[str, None] = '4e9ca77253be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tontines', sa.Column('welcome_message', sa.String(length=300), nullable=True))
    op.add_column('tontines', sa.Column('show_next_beneficiary', sa.Boolean(), nullable=True))
    op.add_column('tontines', sa.Column('payment_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('tontines', 'payment_day')
    op.drop_column('tontines', 'show_next_beneficiary')
    op.drop_column('tontines', 'welcome_message')
    # ### end Alembic commands ###
