"""add_clerk_id

Revision ID: 3bdc55b4557b
Revises: 6c8a13aa9c6c
Create Date: 2026-04-01 11:54:56.691836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdc55b4557b'
down_revision: Union[str, None] = '6c8a13aa9c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
